title: tekiirock's Blog
description: tekiirock's Blog
theme: just-the-docs

url: https://tekiirock.github.io
social_name: tekiirock
social_email: tekiirock@gmail.com

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
